version: '3'

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"  # Map host's port 80 to container's port 80
    networks:
      - api-bridge
    depends_on:
      - api-app
      - webhook-app
    env_file:
      - .env
  
  api-app:
    build:
      context: ./api-app
    ports:
      - "8080:8080"  # Map host's port 8080 to container's port 8080
    networks:
      - api-bridge
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  webhook-app:
    build:
      context: ./webhook-app
    ports:
      - "8000:8000"  # Map host's port 8000 to container's port 8000
    networks:
      - api-bridge
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - api-bridge
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    env_file:
      - .env

networks:
  api-bridge:
    driver: bridge
