version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "80:8080"  # Map host's port 80 to container's port 8080
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    env_file:
      - .env

networks:
  network:
    driver: bridge
